apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-ehr-ui
spec:
  template:
    spec:
      containers:
        - name: ciyex-ehr-ui
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: NEXT_PUBLIC_ENV
              value: "production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
