"use client";

import AdminLayout from "@/app/(admin)/layout";
import { useBilling } from "@/hooks/useBilling";
import { usePagination } from "@/hooks/usePagination";
import Pagination from "@/components/tables/Pagination";
import { Receipt, DollarSign, Clock, AlertCircle } from "lucide-react";

function statusBadge(status?: string) {
    const s = (status || "").toLowerCase();
    const cls =
        s === "balanced" ? "bg-green-100 text-green-700" :
        s === "issued" ? "bg-blue-100 text-blue-700" :
        s === "draft" ? "bg-amber-100 text-amber-700" :
        s === "cancelled" ? "bg-red-100 text-red-700" :
        "bg-gray-100 text-gray-600";
    return <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${cls}`}>{status?.charAt(0).toUpperCase() + (status?.slice(1) || "") || "Unknown"}</span>;
}

function fmtDate(d?: string) {
    if (!d) return "—";
    try {
        const dt = new Date(d);
        return isNaN(dt.getTime()) ? d : dt.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
    } catch { return d; }
}

function fmtMoney(v?: string) {
    const n = parseFloat(v || "0");
    return isNaN(n) ? "$0.00" : `$${n.toFixed(2)}`;
}

export default function BillingPage() {
    const { invoices, loading, error } = useBilling();
    const { currentPage, totalPages, paginatedItems, onPageChange, totalItems, startItem, endItem } = usePagination(invoices, 10);

    const totalAmount = invoices.reduce((sum, inv) => sum + (parseFloat(inv.totalGross || "0") || 0), 0);
    const pendingCount = invoices.filter(inv => inv.status === "issued" || inv.status === "draft").length;

    return (
        <AdminLayout>
            <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 space-y-6">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Billing & Invoices</h1>
                    <p className="text-sm text-gray-500 mt-0.5">View your medical bills and payment history</p>
                </div>

                {loading ? (
                    <div className="flex items-center justify-center py-20">
                        <div className="animate-spin w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full" />
                    </div>
                ) : error ? (
                    <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl p-5">
                        <AlertCircle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
                        <div>
                            <h3 className="text-sm font-semibold text-amber-800">Unable to load billing</h3>
                            <p className="text-sm text-amber-700 mt-1">Please contact your healthcare provider if you believe you should have access.</p>
                        </div>
                    </div>
                ) : invoices.length === 0 ? (
                    <div className="text-center py-16">
                        <Receipt className="h-10 w-10 text-gray-300 mx-auto mb-3" />
                        <h3 className="text-sm font-semibold text-gray-900">No invoices found</h3>
                        <p className="text-sm text-gray-500 mt-1">Your medical invoices will appear here once generated by your provider.</p>
                    </div>
                ) : (
                    <>
                        {/* Summary */}
                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-4 flex items-center gap-3">
                                <div className="p-2 bg-blue-50 rounded-lg"><Receipt className="h-5 w-5 text-blue-600" /></div>
                                <div>
                                    <p className="text-xs text-gray-500">Total Invoices</p>
                                    <p className="text-lg font-bold text-gray-900">{invoices.length}</p>
                                </div>
                            </div>
                            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-4 flex items-center gap-3">
                                <div className="p-2 bg-green-50 rounded-lg"><DollarSign className="h-5 w-5 text-green-600" /></div>
                                <div>
                                    <p className="text-xs text-gray-500">Total Amount</p>
                                    <p className="text-lg font-bold text-gray-900">{fmtMoney(totalAmount.toString())}</p>
                                </div>
                            </div>
                            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-4 flex items-center gap-3">
                                <div className="p-2 bg-amber-50 rounded-lg"><Clock className="h-5 w-5 text-amber-600" /></div>
                                <div>
                                    <p className="text-xs text-gray-500">Pending</p>
                                    <p className="text-lg font-bold text-gray-900">{pendingCount}</p>
                                </div>
                            </div>
                        </div>

                        {/* Table */}
                        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                            <div className="overflow-x-auto">
                                <table className="w-full">
                                    <thead>
                                        <tr className="border-b border-gray-200 bg-gray-50/50">
                                            <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Invoice #</th>
                                            <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Date</th>
                                            <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Amount</th>
                                            <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                                            <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Details</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-gray-100">
                                        {paginatedItems.map((inv: any, i: number) => (
                                            <tr key={inv.id || i} className="hover:bg-gray-50/50 transition-colors">
                                                <td className="px-4 py-3">
                                                    <span className="text-sm font-medium text-gray-900">{inv.invoiceNumber || `INV-${inv.id}`}</span>
                                                    {inv.externalId && <div className="text-xs text-gray-400">Ext: {inv.externalId}</div>}
                                                </td>
                                                <td className="px-4 py-3">
                                                    <span className="text-sm text-gray-700">{fmtDate(inv.issueDate)}</span>
                                                    {inv.dueDate && <div className="text-xs text-gray-400">Due: {fmtDate(inv.dueDate)}</div>}
                                                </td>
                                                <td className="px-4 py-3">
                                                    <span className="text-sm font-semibold text-gray-900">{fmtMoney(inv.totalGross)}</span>
                                                    {inv.totalNet && parseFloat(inv.totalNet) !== parseFloat(inv.totalGross || "0") && (
                                                        <div className="text-xs text-green-600">Paid: {fmtMoney((parseFloat(inv.totalGross || "0") - parseFloat(inv.totalNet)).toString())}</div>
                                                    )}
                                                </td>
                                                <td className="px-4 py-3">{statusBadge(inv.status)}</td>
                                                <td className="px-4 py-3">
                                                    <span className="text-sm text-gray-700">{inv.payer || "Self"}</span>
                                                    {inv.lines?.length > 0 && (
                                                        <div className="text-xs text-gray-400 mt-0.5 space-y-0.5">
                                                            {inv.lines.slice(0, 3).map((line: any, li: number) => (
                                                                <span key={li} className="block">
                                                                    {line.code || line.cptCode || line.serviceCode ? (
                                                                        <span className="font-mono">{line.code || line.cptCode || line.serviceCode}</span>
                                                                    ) : null}
                                                                    {(line.code || line.cptCode || line.serviceCode) && line.description ? " · " : null}
                                                                    {line.description && <span className="truncate">{line.description}</span>}
                                                                    {!line.code && !line.cptCode && !line.serviceCode && !line.description && `Item ${li + 1}`}
                                                                </span>
                                                            ))}
                                                            {inv.lines.length > 3 && <span>+{inv.lines.length - 3} more</span>}
                                                        </div>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                            <div className="px-4 py-3 border-t border-gray-100 bg-gray-50/30 flex items-center justify-between text-xs text-gray-500">
                                <div className="flex items-center gap-4">
                                    <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-green-500" /> Paid</span>
                                    <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-blue-500" /> Issued</span>
                                    <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-amber-500" /> Draft</span>
                                    <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-red-500" /> Cancelled</span>
                                </div>
                                <Pagination
                                    currentPage={currentPage}
                                    totalPages={totalPages}
                                    onPageChange={onPageChange}
                                    totalItems={totalItems}
                                    startItem={startItem}
                                    endItem={endItem}
                                    label="invoices"
                                />
                            </div>
                        </div>
                    </>
                )}
            </div>
        </AdminLayout>
    );
}
