apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

nameSuffix: -stage

images:
  - name: ciyex-portal-ui
    newName: hinikubestageacr.azurecr.io/ciyex-portal-ui-stage
    newTag: stage

replicas:
  - name: ciyex-portal-ui
    count: 1

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: portal-ui-config
    envs:
      - .env.stage
